blaukart/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import TemplateView
from django.conf.urls import (handler400, handler403, handler404, handler500)
from django.conf.urls.i18n import i18n_patterns

import debug_toolbar

urlpatterns = [
	#path('managers/', admin.site.urls, name='managers'),
	path('__debug__/', include(debug_toolbar.urls)),
	#path('', TemplateView.as_view(template_name="shop/index.html"), name="home"),
	path('', include('modules.shop.urls', namespace='shop')),
	path('contacts/', include('modules.support.contacts.urls', namespace='contacts')),
	path('faqs/', include('modules.support.faq.urls', namespace='faqs')),
	path('accounts/', include('modules.appcore.accounts.urls', namespace='accounts')),
	path('payments/', include('modules.payments.urls', namespace='payments')),
]

# Multi-Lingual URL
urlpatterns += i18n_patterns(
	#path('', TemplateView.as_view(template_name="shop/index.html"), name="home"),
	path('', include('modules.shop.urls', namespace='faqs' )),
)

# Error Handlers:
handler404 = 'modules.appcore.accounts.views.error404'
# handler400 = 'modules.appcore.accounts.error_views.bad_request'
# handler403 = 'modules.appcore.accounts.error_views.permission_denied'
# handler404 = 'django.views.defaults.page_not_found'
handler500 = 'modules.appcore.accounts.views.error500'

modules/appcore/accounts/urls.py
from django.urls import path, include

from . import views
from django.contrib.auth import views as auth_views

app_name = 'accounts'

urlpatterns = [
    ##### user related path ##########################
    path('signup/', views.signup, name="signup"),
    path('signuplite/', views.signuplite, name="signuplite"),
    path('login/', views.login_view, name ='login'),

    #path('logout/', auth_views.LogoutView.as_view(template_name ='user/index.html'), name ='logout'),
    #path('logout/', auth_views.LogoutView.as_view(template_name ='accounts/login.html'), name ='logout'),
    path('logout/', views.logout, name ='logout'),

    path('verify_email/', views.verify_email_view, name ='verify_email'),
    path('send_email_otp/', views.send_email_otp, name ='send_email_otp'),

    path('verify_phone/', views.verify_phone_view, name ='verify_phone'),
    path('send_phone_otp/', views.send_phone_otp, name ='send_phone_otp'),

    path('password_change/', views.password_change, name='password_change'),

    path('password_forget/', views.password_forget, name='password_forget'),
    path('password_reset_pending/', views.password_reset_pending, name='password_reset_pending'),
    path('password_reset/<str:token>/', views.password_reset_by_link, name='password_reset_by_link'),
    path('password_reset_otp/', views.password_reset_by_otp, name='password_reset_otp'),
    path('password_reset/', views.password_reset, name ='password_reset'),

    path('user_dashboard/', views.user_dashboard, name ='user_dashboard'),
    path('admin_dashboard/', views.admin_dashboard, name ='admin_dashboard'),
    
    path('user_update/', views.user_update, name ='user_update')
]

modules/appcore/accounts/forms.py
from django import forms
from .models import CustomUser


from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, SetPasswordForm

from django.utils.translation import gettext, gettext_lazy as _

class NameForm(forms.Form):
    your_name = forms.CharField(label='Your name', max_length=100)

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    message = forms.CharField(widget=forms.Textarea)
    sender = forms.EmailField()
    cc_myself = forms.BooleanField(required=False)

#class SignupForm(forms.Form):
#    full_name = forms.CharField(label='Full Name', max_length=30)
#    email = forms.EmailField(label='Email')
#    ph_no = forms.CharField(label='Ph. No.', max_length=15)
#    password = forms.CharField(label='Password', max_length=100)
#    confirm_password = forms.CharField(label='Confirm Password', max_length=100)


class SignupForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['first_name','last_name', 'username', 'email', 'ph_no', 'password']

    confirm_password = forms.CharField(label='Confirm Password', max_length=100)


class UserRegisterForm(UserCreationForm):
    #email = forms.EmailField()
    #ph_no = forms.CharField(max_length = 20)
    #full_name = forms.CharField(max_length = 20)
    class Meta:
        model = CustomUser
        fields = ['first_name','last_name', 'username',  'email', 'ph_no']



class UserRegisterLiteForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['email']
        #fields = []


class LoginForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['email', 'password']



class LoginForm(AuthenticationForm):
    #email = forms.CharField(label='Email ID')
    class Meta:
        model = CustomUser
        fields = [ 'email']

class PasswordChangeForm(AuthenticationForm): #(UserCreationForm):
    old_password = forms.CharField(
        label=_("Old Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}),
    )
    class Meta:
        model = CustomUser
        fields = ['email', 'old_password', 'password1', 'password2']

    field_order = ['email', 'old_password', 'password1', 'password2']


class PasswordResetForm(SetPasswordForm):

    new_password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}),
    )
    new_password2 = forms.CharField(
        label=_("Re-Enter Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}),
    )

    field_order = ['new_password1', 'new_password2']


class PasswordResetOtpForm(SetPasswordForm):
    otp = forms.CharField(
        label=_("Email OTP"),
        max_length=30,
    )
    new_password1 = forms.CharField(
        label=_("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}),
    )
    new_password2 = forms.CharField(
        label=_("Re-Enter Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}),
    )

    field_order = ['otp', 'new_password1', 'new_password2']


class PasswordForgetForm(forms.Form):
    email = forms.EmailField(
        label=_("Email "),
        max_length=254,
        widget=forms.EmailInput(attrs={'autocomplete': 'email'})
    )
    
    
    
class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'username', 'ph_no']

modules/appcore/accounts/views.py
 
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.core.mail import send_mail
from django.core.mail import EmailMultiAlternatives
from django.template.loader import get_template
from django.template import Context
  
from . import forms as accounts_forms
from .forms import UserRegisterForm, UserRegisterLiteForm, LoginForm, UserUpdateForm#  PasswordChangeForm# AuthenticationForm
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm, SetPasswordForm
from django.contrib.auth import update_session_auth_hash

from django.http import HttpResponse
from django.shortcuts import render, redirect as _redirect


from django.contrib.auth import login, logout, authenticate, views as auth_views
from .forms import SignupForm
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from .tokens import account_activation_token

from django.contrib.auth.models import Group
from django.core.mail import EmailMessage

from .models import CustomUser
from .signals import user_logged_in, user_logged_out, user_login_failed
from .utils import send_sms



HOST_EMAIL = 'subhajit.webkrone@gmail.com'


def redirect(args):
	return _redirect('accounts:'+str(args))



################ sign up ###################################################
def signup(request):    
	if request.method == 'POST':        
		#form = SignupForm(request.POST)
		agree = request.POST["agree"]  
		form = UserRegisterForm(request.POST)         
		if form.is_valid(): 
			if agree: 
				user = form.save(commit=False)   
				print('signup - user created...') 

				#user.is_active = False
				user.is_active = True
				user.save()
				print('signup - user saved...')

				current_site = get_current_site(request)
				user.send_verification_email(from_email=HOST_EMAIL)
				print('signup - verification email sent...')


				'''
				mail_subject = 'Activate your Account.' 
				"""           
				message = render_to_string('accounts/acc_active_email.html', {                
				'user': user,                
				'domain': current_site.domain,                
				'uid':urlsafe_base64_encode(force_bytes(user.pk)),                
				'token':account_activation_token.make_token(user),            
				})            
				"""
				message = f"""
				Hello {user.first_name},	
				Your account is created successfully!
				"""
				to_email = form.cleaned_data.get('email')            
				email = EmailMessage(mail_subject, message, to=[to_email])            
				email.send()
				'''

				request.session.flush()
				print('session flushed...')

				messages.success(request, f'You are successfully registered!!')
				print(f'You are successfully registered!!')
				#messages.info(request, f'Please verify your email address to get full access')
				#print( f'Please verify your email address to get full access')
				return redirect('login')

				#return HttpResponse('Please confirm your email address to complete the registration')

			else:
				messages.warning(request, f'Please check & agree to all Terms & Conditions')
				print(f'Please check & agree to all Terms & Conditions')
				return redirect('signup')

		else:
			messages.error(request, f'Invalid Entry, Please try again!')
			print(f'Invalid Entry, Please try again!')
			return redirect('signup')
			#return HttpResponse('Invalid Entry, Please try again!')
		 
	form = UserRegisterForm()
	return render(request, 'accounts/signup.html', {'form': form})




########################## sign up lite ###################################################
def signuplite(request):   
	try: 
		if request.method == 'POST':
			agree = request.POST["agree"]        
			form = UserRegisterLiteForm(request.POST)         
			
			print(agree)

			if form.is_valid():            
				if agree:
					user = form.save(commit=False)
					print('signuplite - user created...') 


					#user.is_active = False
					user.is_active = True
					user.save()
					print('signuplite - user saved...')

					current_site = get_current_site(request)

					request.session.flush()
					print('session flushed...')

					#login(request, user)
					#print('signup - user logged in...')

					messages.success(request, f'You are successfully registered!!')
					print(f'You are successfully registered!!')
					return redirect('login')
					#return HttpResponse('You are successfully registered!!')

				else:
					messages.warning(request, f'Please check & agree to all Terms & Conditions')
					print(f'Please check & agree to all Terms & Conditions')
					return redirect('signuplite')

			else:
				messages.error(request, f'Invalid Entry, Please try again!')
				print(f'Invalid Entry, Please try again!')
				return redirect('signuplite')
				#return HttpResponse('Invalid Entry, Please try again!')

	except Exception as err:
		messages.warning(request, f'Please check  & agree to all Terms & Conditions')
		print(f'Please check & agree to all Terms & Conditions')


	form = UserRegisterLiteForm()
	return render(request, 'accounts/signuplite.html', {'form': form})



  
############################# login view ###################################################
def login_view(request):
	if request.method == 'POST':
  
		# AuthenticationForm_can_also_be_used__

		email = request.POST['username']
		password = request.POST['password']
		user = authenticate(request, email= email, password = password)
		if user is not None:
			form = login(request, user)
			print(f' Welcome {user.email} !!')
			messages.success(request, f' Welcome {user.email} !!')
			#return redirect('admin_dashboard')
			return redirect('user_dashboard')
		else:
			print(f'Access Denied: Invalid entry / Account does not exist')
			messages.error(request, f'Invalid entry / Account does not exist')
			return redirect('login')

	#form = AuthenticationForm()
	form = LoginForm()
	return render(request, 'accounts/login.html', {'form':form, 'title':'log in'})


"""
def login_view(request):
	if request.method == 'POST':
		m = CustomUser.objects.get(email=request.POST['email'])
		if m.password == m.get_password(request.POST['password']):
			request.session['member_id'] = m.id
			return HttpResponse("You're logged in.")
		else:
			return HttpResponse("Your username and password didn't match.")

	form = LoginForm()
	return render(request, 'accounts/login.html', {'form':form, 'title':'log in'})
"""



################ logout ###################################################
def logout(request):
	"""
		Remove the authenticated user's ID from the request and flush their session
		data.
	"""
	# Dispatch the signal before the user is logged out so the receivers have a
	# chance to find out *who* logged out.
	user = getattr(request, 'user', None)

	if not getattr(user, 'is_authenticated', True):
		user = None
	user_logged_out.send(sender=user.__class__, request=request, user=user)  # Custom pre logged_out signal
	request.session.flush()
	if hasattr(request, 'user'):
		from django.contrib.auth.models import AnonymousUser
		request.user = AnonymousUser()

	param = {}
	return render(request, 'accounts/logout.html', param)



######################## password change ###################################################
'''
def password_change(request):
	if request.method == 'POST':
  
		# AuthenticationForm_can_also_be_used__
  
		email = request.POST['username']
		password = request.POST['old_password']
		user = authenticate(request, email= email, password = password)
		if user is not None:

			new_password = request.POST['password']
			user.set_password(new_password)
			user.save()
			update_session_auth_hash(request,user)

			print( f' Password changed successfully !!')
			messages.success(request, f' Password changed successfully !!')
			return redirect('login')
		else:
			print(f' Account does not exist - Invalid Entry')
			messages.error(request, f'Account does not exist - Invalid Entry ')

	form = PasswordChangeForm()
	return render(request, 'accounts/password_reset.html', {'form':form, 'title':'Password Change'})

'''

def password_change(request):
	user = request.user
	if (hasattr(user, 'email')):

		if request.method == 'POST':
			try:
				form = PasswordChangeForm(user, request.POST)
				if form.is_valid():
					user = form.save()
					update_session_auth_hash(request,user)

					print(f' Password changed successfully !!')
					messages.success(request, f' Password changed successfully !!')
					return redirect('login')
				else:
					print(f'Invalid Entry - Try Again!')
					messages.error(request, f'Invalid Entry - Try Again!')
					return redirect('password_change')
					
			except Exception as err:
				print(f'Invalid Entry - {err}')
				messages.error(request, f'Invalid Entry - {err}')
				return redirect('password_change')

		form = PasswordChangeForm(user)
		return render(request, 'accounts/password_reset.html', {'form': form, 'title': 'Password Change'})

	print(f'You are not authorised - Please Log In!')
	messages.warning(request, f'You are not authorised - Please Log In!')
	return redirect('login')




################ Admin Dashboard ###################################################
#@login_required
def admin_dashboard(request):

	user = request.user
	print("USER IS : ", user)

	try:
		if user.email is not None:

			if not user.email_verified:
				messages.info(request, f'Please verify your email address to get full access')
				print( f'Please verify your email address to get full access')

			if user.is_superuser:
				print("Superuser")
				groups = Group.objects.all()
				users = CustomUser.objects.all()
				param ={
					'groups' : groups,
					'users'  : users,
					'user'   : user,
				 }  # Group, CustomUser, user
				return render(request, 'accounts/admin_dashboard.html', param)
			else:
				print("You are not superuser")

modules/appcore/accounts/templates/accounts/admin_dashboard.html
{% extends 'accounts/base.html' %}

{% block head %}
    <title>User Admin</title> 
{% endblock %}

{% block body %}
    <h2> 
    	User Admin
    </h2>







<div class="container py-5">
    <div class="row">
        <div class="col-md-3">
            <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist" aria-orientation="vertical">
                <a class="nav-link active" id="v-pills-profile-tab" data-toggle="pill" href="#v-pills-profile" role="tab" aria-controls="v-pills-home" aria-selected="true">Profile</a>
                <a class="nav-link" id="v-pills-questions-tab" data-toggle="pill" href="#v-pills-questions" role="tab" aria-controls="v-pills-questions" aria-selected="false">Users</a>
                <a class="nav-link" id="v-pills-questions-tab" data-toggle="pill" href="#v-pills-questions" role="tab" aria-controls="v-pills-questions" aria-selected="false">User</a>
                <a class="nav-link" id="v-pills-questions-tab" data-toggle="pill" href="#v-pills-questions" role="tab" aria-controls="v-pills-questions" aria-selected="false">Groups</a>
            </div>
        </div>
        <div class="col-md-9">
            <div class="tab-content" id="v-pills-tabContent">
                <!-- Profile -->
                <div class="tab-pane fade show active" id="v-pills-profile" role="tabpanel" aria-labelledby="v-pills-profile-tab">
                    <div class="card">
                        <h5 class="card-header">User Profile</h5>
                        <div class="card-body">
                            {% for msg in messages %}
                            <p class="text-success">{{msg}}</p>
                            {% endfor %}
                            <form method="post">
                                {% csrf_token %}
                                <table class="table table-bordered">
                                    {{form.as_table}}
                                    <tr>
                                        <td colspan="2">
                                            <button class="btn btn-primary">Submit</button>
                                        </td>
                                    </tr>
                                </table>
                            </form>
                        </div>
                    </div>
                </div>

                <!--users -->
                <div class="tab-pane fade" id="v-pills-questions" role="tabpanel" aria-labelledby="v-pills-questions-tab">
                    <div class="card">
                        <h5 class="card-header">Member <span class="badge badge-info">{{users}}</span></h5>
                        <div class="card-body">
                        	{% for pro in users %}
                            <p><a href="/detail/{{pro.id}}">{{pro.username}}</a></p>
                            <hr />
                            {% endfor %}
                        </div>
                    </div>
                </div>


                <div class="tab-pane fade" id="v-pills-questions" role="tabpanel" aria-labelledby="v-pills-questions-tab">
                    <div class="card">
                        <h5 class="card-header">User<span class="badge badge-info">{{user.first_name}}</span></h5>
                        <div class="card-body">
                        	
                            <p><a href="/detail/{{user.id}}">{{user}}</a></p>
                            <hr />
                            
                        </div>
                    </div>
                </div>

                <div class="tab-pane fade" id="v-pills-questions" role="tabpanel" aria-labelledby="v-pills-questions-tab">
                    <div class="card">
                        <h5 class="card-header">Groups<span class="badge badge-info">{{groups}}</span></h5>
                        <div class="card-body">
                        	{% for pro in groups %}
                            <p><a href="/detail/{{pro.id}}">{{pro}}</a></p>
                            <hr />
                            {% endfor %}
                        </div>
                    </div>
                </div>






{% endblock %} 

modules/appcore/accounts/templates/accounts/login.html
{% extends 'shop/base.html' %}

{% block title %} Login | Blaukart {% endblock %}

{% block content %}

<section id="form"><!--form-->
    <div class="container">
        <div class="row">

            <div class="col-sm-4 col-sm-offset-1">
                <div class="login-form"><!--login form-->
                    <h2>Login to your account</h2>
                    <form method="post" action="{% url 'accounts:login' %}">
                        {% csrf_token %}
                        {{ form.as_table }}
                        <span>
								<input type="checkbox" class="checkbox">
								Keep me signed in
							</span>
                        <button type="submit" class="btn btn-default">Login</button>
                    </form>
                    <br>
                    <a href="{% url 'accounts:password_forget' %}">Forget Password? </a> ||
                    <a href="{% url 'shop:basic:index' %}">Home</a> <br>
                    <b> Create account > </b><a href="{% url 'accounts:signup' %}">Signup</a>
                </div><!--/login form-->
            </div>


        </div>
    </div>
</section><!--/form-->

{% endblock %}

modules/appcore/accounts/templates/accounts/logout.html
{% extends 'accounts/base.html' %}

{% block head %}
<title>Log Out</title>
{% endblock %}

{% block body %}
<div class="container">
    <div class="card mt-5">
        <h4 class="card-header">You are successfully logged out.</h4>
        <div class="card-body">

            <div class="col-lg-10 d-flex align-items-center justify-content-center">
                <div class="auth-form-transparent text-left p-3">

                    {% load static %}
                    <div class="brand-logo">
                        <img src="{% static 'accounts/images/webkrone_logo1.png' %}" alt="logo">
                    </div>
                    <h6 class="font-weight-light"></h6>

                    <a href="{% url 'accounts:login' %}">Login again </a> ||
                    <a href="{% url 'shop:basic:index' %}">Home</a>

                    </table>
                    </form>


                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %} 

modules/appcore/accounts/templates/accounts/password_forget.html
{% extends 'accounts/base.html' %}

{% block head %}
<title>Password Forget</title>
{% endblock %}

{% block body %}


<div class="container">
    <div class="card mt-5">
        <h4 class="card-header">Forgot Password?</h4>
        <div class="card-body">

            <div class="col-lg-10 d-flex align-items-center justify-content-center">
                <div class="auth-form-transparent text-left p-3">

                    {% load static %}
                    <div class="brand-logo">
                        <img src="{% static 'accounts/images/webkrone_logo1.png' %}" alt="logo">
                    </div>


                    <h6 class="font-weight-light">Enter your email to reset your password. </h6>
                    <form method="POST" class="form-group" action="{% url 'password_forget' %} ">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Submit</button>
                    </form>

                    <h5> Do you have password? </h5><a href="{% url 'login' %}">Login again </a> ||
                    <a href="{% url 'home' %}">Home</a>

                </div>
            </div>

        </div>
    </div>
</div>
{% endblock %}

modules/appcore/accounts/templates/accounts/password_reset.html
{% extends 'accounts/base.html' %}

{% block head %}
<title>Password Reset</title>
{% endblock %}

{% block body %}
<!--
<h1> Password Reset! </h1>
<h2> Enter your new password. </h2>
<form method="POST" class="form-group" action="{% url 'password_reset' %}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-success">Reset Password</button>
</form>
-->

<div class="container">
    <div class="card mt-5">
        <h4 class="card-header"> Password Reset!</h4>
        <div class="card-body">

            <div class="col-lg-10 d-flex align-items-center justify-content-center">
                <div class="auth-form-transparent text-left p-3">

                    {% load static %}
                    <div class="brand-logo">
                        <img src="{% static 'accounts/images/webkrone_logo1.png' %}" alt="logo">
                    </div>

                    <h4>Secure your Account:</h4>
                    <h6 class="font-weight-light">Reset your password.</h6>


                    <form method="post" action="{% url 'password_reset' %}">
                        {% csrf_token %}
                        <table class="table table-bordered">
                            {{ form.as_p }}


                            <td colspan="2">
                                <button class="btn btn-primary">Reset Password</button>
                            </td>
                            </tr>

                        </table>
                        <a href="{% url 'home' %}">Home</a> <br>
                        <b> Create account </b><a href="{% url 'signup' %}">Click Here</a>
                    </form>


                </div>
            </div>

        </div>
    </div>
</div>

{% endblock %} 

modules/appcore/accounts/templates/accounts/password_reset_by_otp.html
{% extends 'accounts/base.html' %}

{% block head %}
<title> OTP Verification!</title>
{% endblock %}

{% block body %}
<!-- <h1> OTP Verification! </h1>
    <h2> Enter your new password. </h2>
    <form method="POST" class="form-group" action="{% url 'password_reset_otp' %}">
        {% csrf_token %}
        <input type="text" id="otp" name="otp" label="OTP">
        <button type="submit" class="btn btn-success">Submit</button>
    </form> -->


<div class="container">
    <div class="card mt-5">
        <h4 class="card-header">OTP Verification!</h4>
        <div class="card-body">

            <div class="col-lg-10 d-flex align-items-center justify-content-center">
                <div class="auth-form-transparent text-left p-3">

                    {% load static %}
                    <div class="brand-logo">
                        <img src="{% static 'accounts/images/webkrone_logo1.png' %}" alt="logo">
                    </div>


                    <h2 class="font-weight-light">Please check Your Email to get OTP </h2>
                    <form method="POST" class="form-group" action="{% url 'password_reset_otp' %}">
                        {% csrf_token %}
                        <input type="text" id="otp" name="otp" label="OTP" placeholder="Enter OTP">
                        <button type="submit" class="btn btn-success">Submit</button>
                    </form>

                    <a href="{% url 'login' %}">Login again </a> ||
                    <a href="{% url 'home' %}">Home</a>
                    {% endblock %}

modules/appcore/accounts/templates/accounts/signup.html
{% extends 'shop/base.html' %}

{% block title %} Signup {% endblock %}

{% block content %}
<!--h1> Sign Up! </h1-->

<section id="form"><!--form-->
    <div class="container">
        <div class="row">

            <div class="col-sm-4">
                <div class="signup-form"><!--sign up form-->
                    <h2>New User Full Signup!</h2>
                    <form method="post" action="{% url 'accounts:signup' %}">
                        {% csrf_token %}
                        {{ form.as_table }}
                        <br>
                        <span>
								<input type="checkbox" class="checkbox" name="agree" id="">
                                <strong> I agree to all Terms & Conditions </strong>
						</span>
                         <br><br>

                        <button type="submit" class="btn btn-default">Signup</button>
                    </form>
                    <br>
                    <b> Aready Member? </b><a href="{% url 'accounts:login' %}">Login</a> <br>
                    <b> Lite Register </b><a href="{% url 'accounts:signuplite' %}">Click Here</a>
                </div><!--/sign up form-->
            </div>

        </div>
    </div>
</section><!--/form-->

{% endblock %}

modules/appcore/accounts/templates/accounts/signuplite.html
{% extends 'shop/base.html' %}

{% block title %} Signup Lite {% endblock %}

{% block content %}
<!--h1> Sign Up Lite! </h1-->

<section id="form"><!--form-->
    <div class="container">
        <div class="row">

            <div class="col-sm-4">
                <div class="login-form"><!--sign up lite form-->
                    <h2>New User Lite Signup!</h2>
                    <form method="post" action="{% url 'accounts:signuplite' %}">
                        {% csrf_token %}
                        {{ form.as_table }}
                         <br>
                        <span>
								<input type="checkbox" class="checkbox" name="agree" id="">
                                <strong> I agree to all Terms & Conditions </strong>
						</span>
                         <br><br>
                        <button type="submit" class="btn btn-default">Signup</button>
                    </form>
                    <br>
                    <b> Aready Member? </b><a href="{% url 'accounts:login' %}">Login</a> <br>
                    <b> Full Register </b><a href="{% url 'accounts:signup' %}">Click Here</a>
                </div><!--/sign up lite form-->
            </div>

        </div>
    </div>
</section><!--/form-->

{% endblock %}