blaukart/urls.py
from django.contrib import admin
from django.urls import path, include

from django.views.generic import TemplateView
from django.conf.urls import (handler400, handler403, handler404, handler500)
from django.conf.urls.i18n import i18n_patterns

import debug_toolbar

urlpatterns = [
	#path('managers/', admin.site.urls, name='managers'),
	path('__debug__/', include(debug_toolbar.urls)),
	#path('', TemplateView.as_view(template_name="shop/index.html"), name="home"),
	path('', include('modules.shop.urls', namespace='shop')),
	path('contacts/', include('modules.support.contacts.urls', namespace='contacts')),
	path('faqs/', include('modules.support.faq.urls', namespace='faqs')),
	path('accounts/', include('modules.appcore.accounts.urls', namespace='accounts')),
	path('payments/', include('modules.payments.urls', namespace='payments')),
]

# Multi-Lingual URL
urlpatterns += i18n_patterns(
	#path('', TemplateView.as_view(template_name="shop/index.html"), name="home"),
	path('', include('modules.shop.urls', namespace='faqs' )),
)

# Error Handlers:
handler404 = 'modules.appcore.accounts.views.error404'
# handler400 = 'modules.appcore.accounts.error_views.bad_request'
# handler403 = 'modules.appcore.accounts.error_views.permission_denied'
# handler404 = 'django.views.defaults.page_not_found'
handler500 = 'modules.appcore.accounts.views.error500'

modules/payments/urls.py
from django.urls import path

from . import views

#from apps.payments.views import payment,payment_success

app_name = 'payments'

urlpatterns = [
    path('<int:id>/', views.payment_initiate, name="payments"),
    path('success/', views.payment_success, name="payment-success"),
]

modules/payments/models.py
from django.db import models

#from django.contrib.auth.models import User
from modules.appcore.accounts.models import CustomUser as User



class Payment(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    purpose = models.CharField(max_length=30)
    amount = models.PositiveIntegerField()
    o_id = models.CharField(max_length=30, null=True)
    amount_paid = models.PositiveIntegerField(null=True)
    amount_due = models.PositiveIntegerField(null=True)
    currency = models.CharField(max_length=10, default="INR")
    offer_id = models.IntegerField(default=None, null=True) 
    status = models.CharField(max_length=15, default="initiated")
    attempts = models.PositiveIntegerField(null=True)
    notes = models.TextField(null=True)
    created_at =  models.PositiveIntegerField(null=True)
    date_time = models.DateTimeField(auto_now_add=True)

    #{'id': 'order_H1GPQiRHlPiDQu', 'entity': 'order', 'amount': 100, 'amount_paid': 0, 'amount_due': 100,
    # 'currency': 'USD', 'receipt': None, 'offer_id': None, 'status': 'created', 'attempts':0, 'notes': [], 'created_at': 1618941001}

    #def __str__(self):
    #    return self.user




class Purchase(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    payments = models.ManyToManyField(Payment)
    purpose = models.CharField(max_length=30)
    amount = models.PositiveIntegerField()
    notes = models.TextField()
    date_time = models.DateTimeField()

    def __str__(self):
        return str(self.user.email) +" : "+ self.purpose +" : "+ str(self.amount)


"""
class Transaction(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    purpose = models.CharField(max_length=30)
    amount = models.PositiveIntegerField()
    notes = models.TextField()
    status = models.CharField(max_length=30)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def __str__(self):
        return str(self.user.email) +" : "+ self.purpose +" : "+ str(self.amount)
"""





class Wallet(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    payments = models.ManyToManyField(Payment)
    balance = models.FloatField(default=0)
    currency = models.CharField(max_length=10, default='INR')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    #def __str__(self):
    #    return self.user

modules/payments/views.py
import os
import razorpay

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt

from django.contrib import messages
from .models import Payment


# TEST KEY
#RAZORPAY_KEY = "rzp_test_pOdnmaU6ec5IWt"
#RAZORPAY_KEY_SECRET = "olR9dGd8I7l3XXZ4KERkDRq7" 

# Live Key
#RAZORPAY_KEY = "rzp_live_4DXpUVE0cjejpJ"
#RAZORPAY_KEY_SECRET = "oviSY94By1rYCsxFbhPX9Hzkd"



# LIVE KEY (working)
#RAZORPAY_KEY = "rzp_live_U1WZUzR2bDRJxl"
#RAZORPAY_KEY_SECRET = "6N2FrVW70ov6nEyQH7QJzVXf"

# TEST KEY (working)
RAZORPAY_KEY = "rzp_test_k9FYjaYUbjtrvz"
RAZORPAY_KEY_SECRET = "JMvGj6aiAsmMa80Ct14ngstJ"



# Payment Initiation:
def payment_initiate(request, id):

    #################### Checking User Log In: ##########################
    FAILED = False
    user = request.user
    try:
        if user.email is None:
            FAILED = True

    except Exception as err:
        print(f"ErrorType- {type(err)}")
        print(f"Error- {err}")

        FAILED = True
    

    if FAILED:
        messages.warning(request, f"Please Log In before making payment")
        print(f"Please Log In before making payment")

        # Returns None if user came from another website
        url = request.META.get('HTTP_REFERER')
        print(f"Redirecting to - {url}")

        if url is not None:
            return redirect(url)
        return redirect('shop:basic:home')

    else:
        print(f"Get user :{user}")




    #################### Getting Payment details by 'id' ##########################
    FAILED = False
    payment = None
    try:
        payment = Payment.objects.get(id=id)
        if payment is None:
            FAILED = True

    except Exception as err:
        print(f"ErrorType- {type(err)}")
        print(f"Error- {err}")

        FAILED = True
        

    if FAILED:
        messages.warning(request, f"Payment not initiated!")
        print( f'Payment not initiated!')

        # Returns None if user came from another website
        url = request.META.get('HTTP_REFERER')
        print(f"Redirecting to - {url}")

        if url is not None:
            return redirect(url)
        return redirect('shop:basic:home')

    else:
        print(f"Get Payment details by id: {id}")




    #################### Checking whether User is same as Payment User or not ##########################
    FAILED = False
    try:
        if user != payment.user:
            FAILED = True

    except Exception as err:
        print(f"ErrorType- {type(err)}")
        print(f"Error- {err}")

        FAILED = True
    

    if FAILED:
        messages.warning(request, f"Sorry! Present payment is not initiated by you")
        print(f"Sorry! Present payment is not initiated by you")

        # Returns None if user came from another website
        url = request.META.get('HTTP_REFERER')
        print(f"Redirecting to - {url}")

        if url is not None:
            return redirect(url)
        return redirect('shop:basic:home')

    else:
        print(f"Get user :{user}")




    #################### Getting Payment 'status' ##########################
    FAILED = False
    status = None
    try:
        status = payment.status
        if(status == 'done'):
            FAILED = True

    except Exception as err:
        print(f"ErrorType- {type(err)}")
        print(f"Error- {err}")

        FAILED = True


    if FAILED:
        messages.warning(request, f"This Payment is Previously done! - Try Again")
        print( f"This Payment is Previously done! - Try Again")

        # Returns None if user came from another website
        url = request.META.get('HTTP_REFERER')
        print(f"Redirecting to - {url}")
        
        if url is not None:
            return redirect(url)
        return redirect('shop:basic:home')

    else:
        print(f"Get Payment status: {status}")




    #################### Getting Payment 'amount' ##########################
    amount = payment.amount

    if(amount<1):
        amount = 1   #100 here means 1 dollar, 1 rupree if currency INR

    amount *= 100

    # client = razorpay.Client(auth=(os.getenv('razorpaykey'), os.getenv('razorpaysecret')))
    client = razorpay.Client(auth=(RAZORPAY_KEY, RAZORPAY_KEY_SECRET) )
    response = client.order.create({'amount': amount,'currency':'INR','payment_capture':1})
    # respose {'id': 'order_H1GPQiRHlPiDQu', 'entity': 'order', 'amount': 100, 'amount_paid': 0, 'amount_due': 100,
    # 'currency': 'USD', 'receipt': None, 'offer_id': None, 'status': 'created', 'attempts':0, 'notes': [], 'created_at': 1618941001}
    print(response)

    payment.o_id = response['id']

    payment.amount_paid = response['amount_paid']
    payment.amount_due = response['amount_due']

    payment.offer_id = response['offer_id']
    payment.status = response['status']
    payment.attempts = response['attempts']
    payment.notes = response['notes']
    payment.created_at =  response['created_at']

    payment.save()

    request.session['payment'] = payment.id

    url = request.META.get('HTTP_REFERER')
    print(f"last_url - {url}")
    if url is None:
        request.session['url'] = '#'
    else:
        request.session['url'] = url

   
    param = {'response': response, 'api_key' : RAZORPAY_KEY, 'pay_amount':amount/100}
    return render(request,"payments/payment.html", param)






# Payment Success View:
@csrf_exempt
def payment_success(request):
    print("---success---")

    #################### Checking User Log In: ##########################
    FAILED = False
    user = request.user
    try:
        if user.email is None:
            FAILED = True

    except Exception as err:
        print(f"ErrorType- {type(err)}")
        print(f"Error- {err}")

        FAILED = True
    

    if FAILED:
        messages.warning(request, f"Please Log In before making payment")
        print(f"Please Log In before making payment")

        # Returns None if user came from another website
        url = request.META.get('HTTP_REFERER')
        print(f"Redirecting to - {url}")

        if url is not None:
            return redirect(url)
        return redirect('shop:basic:home')

    else:
        print(f"Get user :{user}")




    #################### Getting Payment details by 'id' ##########################
    FAILED = False
    payment = None
    try:
        id = request.session['payment']
        payment = Payment.objects.get(id=id)
        if payment is None:
            FAILED = True

    except Exception as err:
        print(f"ErrorType- {type(err)}")
        print(f"Error- {err}")

        FAILED = True
        

    if FAILED:
        messages.warning(request, f"Payment not initiated!")
        print( f'Payment not initiated!')

        # Returns None if user came from another website
        url = request.META.get('HTTP_REFERER')
        print(f"Redirecting to - {url}")
        
        if url is not None:
            return redirect(url)
        return redirect('shop:basic:home')

    else:
        print(f"Get Payment details by id: {id}")




    #################### Checking whether User is same as Payment User or not ##########################
    FAILED = False
    try:
        if user != payment.user:
            FAILED = True

    except Exception as err:
        print(f"ErrorType- {type(err)}")
        print(f"Error- {err}")

        FAILED = True
    

    if FAILED:
        messages.warning(request, f"Sorry! Present payment is not initiated by you")
        print(f"Sorry! Present payment is not initiated by you")

        # Returns None if user came from another website
        url = request.META.get('HTTP_REFERER')
        print(f"Redirecting to - {url}")

        if url is not None:
            return redirect(url)
        return redirect('shop:basic:home')

    else:
        print(f"Get user :{user}")


    if request.method =="POST":
        print('-----')
        print(request.POST)
        print(payment)

        payment.status = "done"
        payment.save()
        print("payment satus saved")

        url = request.session['url']
        request.session['url'] = ""
        print(f"Back url - {url}")

        #return HttpResponse("Done payment hurrey!")
        return render(request, 'payments/success.html', {'last_url':url})


    ##### if request.method == "GET":
    url = request.META.get('HTTP_REFERER')
    print(f"last_url - {url}")
    if url is None:
        return redirect('shop:basic:home')
    else:
        return redirect(url)

modules/payments/templates/payments/payment.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">


    <title>Payment</title>
</head>
<body>

    {% if response %}

    <div class="container">
        <div class="card mt-5">
            <h4 class="card-header">Quick Pay!</h4>
            <div class="card-body">

           <div class="col-lg-10 d-flex align-items-center justify-content-center">
            <div class="auth-form-transparent text-left p-3">

              {% load static %}
              <div class="brand-logo">
                <img src="{% static 'accounts/images/webkrone_logo1.png' %}" alt="logo">
              </div>

              <h4>Make your Payment... </h4>
              <h6 class="font-weight-light">PAY Rs.  {{pay_amount}} <br></h6>

                <!--form action="/payments/success/" method="POST"-->
                <form action="{% url 'payments:payment-success' %}" method="POST">
                    {% csrf_token %}
                    <!--table class="table table-bordered"-->
                                   {{ form.as_p }}
                                   <div class="form-check">
                                            <label class="form-check-label text-muted">
                                              <input type="checkbox" class="form-check-input" name="agree" id="agree">
                                              I agree to all Terms & Conditions <br>
                                            </label>
                                    </div>
                                    <script
                                            src="https://checkout.razorpay.com/v1/checkout.js"
                                            data-key= {{api_key}}
                                            data-amount={{response.amount}}
                                            data-currency={{response.currency}}
                                            data-order_id={{response.id}}
                                            data-buttontext="Pay with Razorpay"
                                            data-name="Razorpay Quick Payment"
                                            data-description="Make your Payment in just 2 step"
                                            data-image="https://www.google.com/url?sa=i&url=https%3A%2F%2Fwebkrone.com%2F&psig=AOvVaw0cPtTQrn68wEnd_8Fa3z5z&ust=1619032741246000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCNiHhpXFjfACFQAAAAAdAAAAABAE"
                                            data-prefill.name={{request.user.first_name}}
                                            data-prefill.email={{request.user.email}}
                                            data-theme.color="#5472F3"
                                        ></script>
                                    <input type="hidden" custom="Hidden Element" name="hidden">

                    <!--/table-->       
                 </form>

              </div>
             </div>   

            </div>
        </div>
    </div>


    
    {% endif %}

      <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>

modules/payments/templates/payments/success.html
{% extends 'accounts/base.html' %}

{% block head %}
    <title>Payment Done!</title> 
{% endblock %}

{% block body %}
        <div class="container">
        <div class="card mt-5">
            <h4 class="card-header">Payment Done!</h4>
            <div class="card-body">

           <div class="col-lg-10 d-flex align-items-center justify-content-center">
            <div class="auth-form-transparent text-left p-3">

              {% load static %}
              <div class="brand-logo">
                <img src="{% static 'accounts/images/webkrone_logo1.png' %}" alt="logo">
              </div>
              <h6 class="font-weight-light">Your payment is successfully made</h6>

                        <a href="{{last_url}}"> Back </a>   || 
                        <a href="{% url 'home' %}"> Home </a>

                    </table>
                </form>


              </div>
             </div>   

            </div>
        </div>
    </div>
{% endblock %} 